stages:
  - build
  - test
  - deploy
  - mirror

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    # 1) Autentica no GitLab Container Registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
    # 2) Build e tag da imagem
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    # 3) Push da imagem autenticado
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - main

test:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt pytest pytest-cov
    - pytest --cov=app
  artifacts:
    paths:
      - htmlcov/

deploy:
  stage: deploy
  when: manual
  script:
    - docker service update \
        --image "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" \
        taskboard_web

mirror:
  stage: mirror
  image: alpine/git
  before_script:
    # Prepara diretório SSH
    - mkdir -p ~/.ssh
    # Injeta a chave privada no arquivo de deploy
    - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_ed25519_mirror
    - chmod 600 ~/.ssh/id_ed25519_mirror
    # Confia no host GitHub sem prompt
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    # Configura Git para usar essa chave
    - git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519_mirror -o UserKnownHostsFile=$HOME/.ssh/known_hosts"
  script:
    # Adiciona remoto GitHub (ignora se já existir)
    - git remote add github ssh://git@github.com:theunrealryan/devops-api-flask.git || true
    # Garante que a branch main exista
    - git fetch github main || git push github main
    # Espelha a branch main
    - git push github main
  only:
    - main
  when: on_success