name: Test, Build, and Deploy to Swarm

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Run tests with pytest
        run: pytest

  build-and-push:
    needs: test
    runs-on: linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-api-flask:latest

  deploy:
    needs: build-and-push
    runs-on: linux-amd64
    steps:
      - name: Deploy to Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SWARM_HOST }}
          username: ${{ secrets.SWARM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/docker/stacks/traefik-stack
            docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-api-flask:latest
            docker stack deploy -c docker-compose.yml traefik
            echo "Deploy finalizado com sucesso!"
