name: Test, Build, and Deploy to Swarm

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and Dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install -r requirements.txt
          python3 -m pip install pytest pytest-cov

      - name: Run tests with pytest
        run: python3 -m pytest

  build-and-push:
    needs: test
    runs-on: linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Etapa para instalar o Docker usando o script oficial
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-api-flask:latest
          build-args: |
            CACHE_BUSTER=${{ gitea.run_id }}

  deploy:
    needs: build-and-push
    runs-on: linux-amd64
    steps:
      - name: Deploy to Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SWARM_HOST }}
          username: ${{ secrets.SWARM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/docker/stacks/traefik-stack
            docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-api-flask:latest
            docker stack deploy -c docker-compose.yml traefik
            echo "Deploy finalizado com sucesso!"
